// Generated by tools/wasm/generate-layout.mjs. Do not edit by hand.
//
// The wasm32 layout of every CNA C ABI structure the WebAssembly backend writes or reads,
// measured from a probe compiled by the Emscripten toolchain that builds the artifact. These
// are not the native offsets: a wasm32 pointer is four bytes, so the native ABI baseline would
// place several of these fields somewhere the module does not look.

/** One structure's wasm32 size, alignment and field offsets. */
export interface WasmStructLayout {
  readonly size: number;
  readonly align: number;
  readonly fields: Readonly<Record<string, { readonly offset: number; readonly size: number }>>;
}

/** Size in bytes of a wasm32 pointer. */
export const WASM_POINTER_SIZE = 4;

/** Emscripten `addFunction` signature strings for the callbacks the backend installs. */
export const WASM_CALLBACK_SIGNATURES = {
  CNA_GameLifecycleCallback: "ijiii",
  CNA_GameBeginDrawCallback: "ijiiii",
} as const;

/** Measured wasm32 layouts, keyed by CNA structure name. */
export const WASM_STRUCT_LAYOUTS = {
  CNA_StringView: {
    size: 16,
    align: 8,
    fields: {
      data: { offset: 0, size: 4 },
      byte_length: { offset: 8, size: 8 },
    },
  },
  CNA_CallbackError: {
    size: 24,
    align: 8,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      message: { offset: 8, size: 16 },
    },
  },
  CNA_GameTime: {
    size: 24,
    align: 8,
    fields: {
      total_game_time_ticks: { offset: 0, size: 8 },
      elapsed_game_time_ticks: { offset: 8, size: 8 },
      is_running_slowly: { offset: 16, size: 1 },
    },
  },
  CNA_GameCallbacks: {
    size: 32,
    align: 4,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      load_content: { offset: 8, size: 4 },
      update: { offset: 12, size: 4 },
      draw: { offset: 16, size: 4 },
      unload_content: { offset: 20, size: 4 },
      exiting: { offset: 24, size: 4 },
      context: { offset: 28, size: 4 },
    },
  },
  CNA_GameFrameHooks: {
    size: 32,
    align: 4,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      initialize: { offset: 8, size: 4 },
      begin_run: { offset: 12, size: 4 },
      end_run: { offset: 16, size: 4 },
      begin_draw: { offset: 20, size: 4 },
      end_draw: { offset: 24, size: 4 },
      context: { offset: 28, size: 4 },
    },
  },
  CNA_GameCreateInfo: {
    size: 48,
    align: 8,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      is_fixed_time_step: { offset: 8, size: 1 },
      target_elapsed_time_ticks: { offset: 16, size: 8 },
      window_title: { offset: 24, size: 16 },
      callbacks: { offset: 40, size: 4 },
    },
  },
  CNA_RendererInfo: {
    size: 32,
    align: 8,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      renderer_name_byte_length: { offset: 8, size: 8 },
      capability_flags: { offset: 16, size: 8 },
      renderer_type: { offset: 24, size: 4 },
      max_texture_dimension: { offset: 28, size: 4 },
    },
  },
  CNA_Rectangle: {
    size: 16,
    align: 4,
    fields: {
      x: { offset: 0, size: 4 },
      y: { offset: 4, size: 4 },
      width: { offset: 8, size: 4 },
      height: { offset: 12, size: 4 },
    },
  },
  CNA_Vector2: {
    size: 8,
    align: 4,
    fields: {
      x: { offset: 0, size: 4 },
      y: { offset: 4, size: 4 },
    },
  },
  CNA_Color: {
    size: 4,
    align: 1,
    fields: {
      r: { offset: 0, size: 1 },
      g: { offset: 1, size: 1 },
      b: { offset: 2, size: 1 },
      a: { offset: 3, size: 1 },
    },
  },
  CNA_Texture2DCreateInfo: {
    size: 24,
    align: 4,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      width: { offset: 8, size: 4 },
      height: { offset: 12, size: 4 },
      mip_map: { offset: 16, size: 1 },
      format: { offset: 20, size: 4 },
    },
  },
  CNA_Texture2DDecodeInfo: {
    size: 24,
    align: 4,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      width: { offset: 8, size: 4 },
      height: { offset: 12, size: 4 },
      zoom: { offset: 16, size: 1 },
    },
  },
  CNA_Texture2DInfo: {
    size: 24,
    align: 4,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      width: { offset: 8, size: 4 },
      height: { offset: 12, size: 4 },
      level_count: { offset: 16, size: 4 },
      format: { offset: 20, size: 4 },
    },
  },
  CNA_Texture2DTransfer: {
    size: 48,
    align: 8,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      level: { offset: 8, size: 4 },
      has_rectangle: { offset: 12, size: 1 },
      rectangle: { offset: 16, size: 16 },
      start_index: { offset: 32, size: 8 },
      element_count: { offset: 40, size: 8 },
    },
  },
  CNA_SpriteBatchBeginInfo: {
    size: 16,
    align: 4,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      sort_mode: { offset: 8, size: 4 },
    },
  },
  CNA_SpriteScaledCommand: {
    size: 72,
    align: 8,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      texture: { offset: 8, size: 8 },
      position: { offset: 16, size: 8 },
      source: { offset: 24, size: 16 },
      color: { offset: 40, size: 4 },
      rotation: { offset: 44, size: 4 },
      origin: { offset: 48, size: 8 },
      scale: { offset: 56, size: 8 },
      effects: { offset: 64, size: 4 },
      layer_depth: { offset: 68, size: 4 },
    },
  },
  CNA_KeyboardState: {
    size: 40,
    align: 8,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      pressed_key_words: { offset: 8, size: 32 },
    },
  },
  CNA_MouseState: {
    size: 32,
    align: 4,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      x: { offset: 8, size: 4 },
      y: { offset: 12, size: 4 },
      scroll_wheel: { offset: 16, size: 4 },
      horizontal_scroll_wheel: { offset: 20, size: 4 },
      pressed_buttons: { offset: 24, size: 4 },
    },
  },
  CNA_GraphicsRendererFallbackRecord: {
    size: 16,
    align: 4,
    fields: {
      struct_size: { offset: 0, size: 4 },
      struct_version: { offset: 4, size: 4 },
      type: { offset: 8, size: 4 },
      reason: { offset: 12, size: 4 },
    },
  },
} as const satisfies Readonly<Record<string, WasmStructLayout>>;
