// Generated by tools/backend/generate-backend-base.mjs. Do not edit by hand.
//
// One abstract class per private backend interface, whose every member refuses with the member's
// own name. A backend that implements part of the boundary extends the matching class and
// overrides what it actually reaches, so an unimplemented route is a truthful refusal instead of
// a silent gap, and a member added to an interface reaches every partial backend at once.

import type { PlayerIndex } from "../Microsoft/Xna/Framework/PlayerIndex.js";
import type { NativeHandle } from "./ownership.js";
import type { NativeResourceLifetime } from "./ownership.js";
import type { GamePadDeadZone } from "../Microsoft/Xna/Framework/Input/Enums.js";
import type { GamePadCapabilities, GamePadState, } from "../Microsoft/Xna/Framework/Input/GamePadValues.js";
import type { KeyboardState } from "../Microsoft/Xna/Framework/Input/KeyboardState.js";
import type { MouseState } from "../Microsoft/Xna/Framework/Input/MouseState.js";
import type { TouchCollection } from "../Microsoft/Xna/Framework/Input/Touch/TouchCollection.js";
import type { GestureSample, TouchPanelCapabilities, } from "../Microsoft/Xna/Framework/Input/Touch/TouchValues.js";
import type { DisplayOrientation } from "../Microsoft/Xna/Framework/DisplayOrientation.js";
import type { DepthFormat, GraphicsProfile, SurfaceFormat, } from "../Microsoft/Xna/Framework/Graphics/DeviceEnums.js";
import type {
  AccelerometerReadingSnapshot,
  AudioEmitterSnapshot,
  AudioListenerSnapshot,
  AudioVectorSnapshot,
  BackendKind,
  BackendRendererInfo,
  BlendStateSnapshot,
  CameraInventorySnapshot,
  CnaAudioBackend,
  CnaBackend,
  CnaContentBackend,
  CnaDeviceBackend,
  CnaEffectBackend,
  CnaExtendedInputBackend,
  CnaGameCallbacks,
  CnaGameConfiguration,
  CnaGameTimeSnapshot,
  CnaGameWindowBackend,
  CnaGamerServicesBackend,
  CnaGraphicsBackend,
  CnaGraphicsExtensionBackend,
  CnaMediaBackend,
  CnaRuntimeServicesBackend,
  CnaSensorBackend,
  CnaStorageBackend,
  CnaVideoBackend,
  CnaXactBackend,
  CnbChunkEntrySnapshot,
  CnbCurveSnapshot,
  CnbDocumentSnapshot,
  CnbExternalReferenceSnapshot,
  CnbGlyphSnapshot,
  CnbKeyframeSnapshot,
  CnbMaterialSnapshot,
  CnbModelInfoSnapshot,
  CnbModelPartSnapshot,
  CnbSoundEffectInfoSnapshot,
  CnbSpriteFontInfoSnapshot,
  CnbTextureInfoSnapshot,
  CnbVideoInfoSnapshot,
  ContentLostResourceKind,
  CueSnapshot,
  DepthStencilStateSnapshot,
  GameWindowBoundsSnapshot,
  GraphicsManagerConfiguration,
  HapticCapabilitiesSnapshot,
  HostDeviceSnapshot,
  JoystickCapabilitiesSnapshot,
  JoystickInfoSnapshot,
  JoystickStateSnapshot,
  MediaSongPlaybackSnapshot,
  MediaSourceSnapshot,
  MicrophoneSnapshot,
  NativeEffectPassSnapshot,
  NativeEffectReflectionSnapshot,
  NativeEffectTechniqueSnapshot,
  PassTimingSnapshot,
  PbrMaterialDefaults,
  PlatformSnapshot,
  PostProcessFrameSnapshot,
  PreferredLocaleSnapshot,
  RasterizerStateSnapshot,
  RenderPipelineSettingsDefaults,
  RenderPipelineStatisticsSnapshot,
  RenderTargetBindingSnapshot,
  RenderTargetInfo,
  RendererDetailSnapshot,
  RendererFallbackSnapshot,
  RendererIdentitySnapshot,
  RendererSelectionSnapshot,
  SamplerStateSnapshot,
  SensorStateSnapshot,
  SensorSupportSnapshot,
  SoundEffectInstanceSnapshot,
  SpriteBatchCommand,
  StockEffectSnapshot,
  StorageDeviceSnapshot,
  Texture2DInfo,
  Texture2DTransfer,
  Texture3DInfo,
  TextureCubeInfo,
  VertexBufferBindingSnapshot,
  VertexElementSnapshot,
  VideoFrameSnapshot,
  VideoPlayerSnapshot,
} from "./backend.js";

/** Refusing base for {@link CnaGameWindowBackend}. */
export abstract class CnaGameWindowBackendBase implements CnaGameWindowBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public getGameWindowAllowUserResizing(
  ): boolean { return this.unsupported("getGameWindowAllowUserResizing"); }
  public setGameWindowAllowUserResizing(
    _value: boolean,
  ): void { return this.unsupported("setGameWindowAllowUserResizing"); }
  public getGameWindowClientBounds(
  ): GameWindowBoundsSnapshot { return this.unsupported("getGameWindowClientBounds"); }
  public getGameWindowCurrentOrientation(
  ): number { return this.unsupported("getGameWindowCurrentOrientation"); }
  public getGameWindowHandle(): bigint { return this.unsupported("getGameWindowHandle"); }
  public getGameWindowScreenDeviceName(): string { return this.unsupported("getGameWindowScreenDeviceName"); }
  public getGameWindowTitle(): string { return this.unsupported("getGameWindowTitle"); }
  public setGameWindowTitle(_value: string): void { return this.unsupported("setGameWindowTitle"); }
  public beginGameWindowScreenDeviceChange(
    _willBeFullScreen: boolean,
  ): void { return this.unsupported("beginGameWindowScreenDeviceChange"); }
  public endGameWindowScreenDeviceChange(
    _name: string,
    _width: number,
    _height: number,
  ): void { return this.unsupported("endGameWindowScreenDeviceChange"); }
  public subscribeGameWindowEvent(
    _event: number,
    _callback: () => void,
  ): NativeHandle { return this.unsupported("subscribeGameWindowEvent"); }
  public unsubscribeGameWindowEvent(
    _registration: NativeHandle,
  ): void { return this.unsupported("unsubscribeGameWindowEvent"); }
}

/** Refusing base for {@link CnaGraphicsBackend}. */
export abstract class CnaGraphicsBackendBase implements CnaGraphicsBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public getGraphicsDeviceStatus(
    _device: NativeHandle,
  ): number { return this.unsupported("getGraphicsDeviceStatus"); }
  public setGraphicsDeviceBlendFactor(
    _device: NativeHandle,
    _packedColor: number,
  ): void { return this.unsupported("setGraphicsDeviceBlendFactor"); }
  public setGraphicsDeviceBlendState(
    _device: NativeHandle,
    _state: BlendStateSnapshot,
  ): void { return this.unsupported("setGraphicsDeviceBlendState"); }
  public setGraphicsDeviceDepthStencilState(
    _device: NativeHandle,
    _state: DepthStencilStateSnapshot,
  ): void { return this.unsupported("setGraphicsDeviceDepthStencilState"); }
  public setGraphicsDeviceRasterizerState(
    _device: NativeHandle,
    _state: RasterizerStateSnapshot,
  ): void { return this.unsupported("setGraphicsDeviceRasterizerState"); }
  public setGraphicsDeviceSamplerState(
    _device: NativeHandle,
    _shaderStage: number,
    _slot: number,
    _state: SamplerStateSnapshot,
  ): void { return this.unsupported("setGraphicsDeviceSamplerState"); }
  public setGraphicsDeviceTexture(
    _device: NativeHandle,
    _shaderStage: number,
    _slot: number,
    _texture: NativeHandle | null,
  ): void { return this.unsupported("setGraphicsDeviceTexture"); }
  public setGraphicsDeviceMultiSampleMask(
    _device: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setGraphicsDeviceMultiSampleMask"); }
  public setGraphicsDeviceReferenceStencil(
    _device: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setGraphicsDeviceReferenceStencil"); }
  public setGraphicsDeviceScissorRectangle(
    _device: NativeHandle,
    _x: number,
    _y: number,
    _width: number,
    _height: number,
  ): void { return this.unsupported("setGraphicsDeviceScissorRectangle"); }
  public setGraphicsDeviceViewport(
    _device: NativeHandle,
    _x: number,
    _y: number,
    _width: number,
    _height: number,
    _minDepth: number,
    _maxDepth: number,
  ): void { return this.unsupported("setGraphicsDeviceViewport"); }
  public setGraphicsDeviceVertexBuffers(
    _device: NativeHandle,
    _bindings: readonly VertexBufferBindingSnapshot[],
  ): void { return this.unsupported("setGraphicsDeviceVertexBuffers"); }
  public setGraphicsDeviceIndexBuffer(
    _device: NativeHandle,
    _buffer: NativeHandle | null,
  ): void { return this.unsupported("setGraphicsDeviceIndexBuffer"); }
  public drawPrimitives(
    _device: NativeHandle,
    _primitiveType: number,
    _startVertex: number,
    _primitiveCount: number,
  ): void { return this.unsupported("drawPrimitives"); }
  public drawIndexedPrimitives(
    _device: NativeHandle,
    _primitiveType: number,
    _baseVertex: number,
    _minVertexIndex: number,
    _numVertices: number,
    _startIndex: number,
    _primitiveCount: number,
  ): void { return this.unsupported("drawIndexedPrimitives"); }
  public drawInstancedPrimitives(
    _device: NativeHandle,
    _primitiveType: number,
    _baseVertex: number,
    _minVertexIndex: number,
    _numVertices: number,
    _startIndex: number,
    _primitiveCount: number,
    _instanceCount: number,
  ): void { return this.unsupported("drawInstancedPrimitives"); }
  public drawUserPrimitives(
    _device: NativeHandle,
    _primitiveType: number,
    _vertexSource: number,
    _bytes: Uint8Array,
    _vertexStride: number,
    _vertexCapacity: number,
    _vertexOffset: number,
    _numVertices: number,
    _primitiveCount: number,
    _declaration: readonly VertexElementSnapshot[] | null,
  ): void { return this.unsupported("drawUserPrimitives"); }
  public drawUserIndexedPrimitives(
    _device: NativeHandle,
    _primitiveType: number,
    _vertexSource: number,
    _bytes: Uint8Array,
    _vertexStride: number,
    _vertexCapacity: number,
    _vertexOffset: number,
    _numVertices: number,
    _primitiveCount: number,
    _declaration: readonly VertexElementSnapshot[] | null,
    _indexBytes: Uint8Array,
    _indexElementSize: number,
    _indexCapacity: number,
    _indexOffset: number,
  ): void { return this.unsupported("drawUserIndexedPrimitives"); }
  public beginSpriteBatchWithStates(
    _spriteBatch: NativeHandle,
    _sortMode: number,
    _blend: BlendStateSnapshot,
    _sampler: SamplerStateSnapshot,
    _depth: DepthStencilStateSnapshot,
    _rasterizer: RasterizerStateSnapshot,
    _transform: readonly number[] | null,
  ): void { return this.unsupported("beginSpriteBatchWithStates"); }
  public setVertexBufferData(
    _buffer: NativeHandle,
    _vertexType: number,
    _options: number,
    _startIndex: number,
    _elementCount: number,
    _capacity: number,
    _bytes: Uint8Array,
  ): void { return this.unsupported("setVertexBufferData"); }
  public setVertexBufferRawAt(
    _buffer: NativeHandle,
    _offsetInBytes: number,
    _bytes: Uint8Array,
    _vertexCount: number,
    _vertexStride: number,
    _options: number,
  ): void { return this.unsupported("setVertexBufferRawAt"); }
  public getVertexBufferRawAt(
    _buffer: NativeHandle,
    _offsetInBytes: number,
    _vertexCount: number,
    _vertexStride: number,
  ): Uint8Array { return this.unsupported("getVertexBufferRawAt"); }
  public getVertexBufferIsContentLost(
    _buffer: NativeHandle,
  ): boolean { return this.unsupported("getVertexBufferIsContentLost"); }
  public subscribeContentLost(
    _kind: ContentLostResourceKind,
    _resource: NativeHandle,
    _callback: () => void,
  ): NativeHandle { return this.unsupported("subscribeContentLost"); }
  public unsubscribeContentLost(
    _registration: NativeHandle,
  ): void { return this.unsupported("unsubscribeContentLost"); }
  public setIndexBufferData(
    _buffer: NativeHandle,
    _elementSize: number,
    _options: number,
    _offsetInBytes: number | null,
    _startIndex: number,
    _elementCount: number,
    _capacity: number,
    _bytes: Uint8Array,
  ): void { return this.unsupported("setIndexBufferData"); }
  public getIndexBufferIsContentLost(
    _buffer: NativeHandle,
  ): boolean { return this.unsupported("getIndexBufferIsContentLost"); }
  public createTexture3D(
    _device: NativeHandle,
    _width: number,
    _height: number,
    _depth: number,
    _mipMap: boolean,
    _format: number,
  ): NativeHandle { return this.unsupported("createTexture3D"); }
  public getTexture3DInfo(
    _texture: NativeHandle,
  ): Texture3DInfo { return this.unsupported("getTexture3DInfo"); }
  public setTexture3DColors(
    _texture: NativeHandle,
    _level: number,
    _left: number,
    _top: number,
    _right: number,
    _bottom: number,
    _front: number,
    _back: number,
    _startIndex: number,
    _elementCount: number,
    _packedColors: Uint32Array,
  ): void { return this.unsupported("setTexture3DColors"); }
  public getTexture3DColors(
    _texture: NativeHandle,
    _level: number,
    _left: number,
    _top: number,
    _right: number,
    _bottom: number,
    _front: number,
    _back: number,
    _startIndex: number,
    _elementCount: number,
    _capacity: number,
  ): Uint32Array { return this.unsupported("getTexture3DColors"); }
  public destroyTexture3D(_texture: NativeHandle): void { return this.unsupported("destroyTexture3D"); }
  public createTextureCube(
    _device: NativeHandle,
    _size: number,
    _mipMap: boolean,
    _format: number,
  ): NativeHandle { return this.unsupported("createTextureCube"); }
  public getTextureCubeInfo(
    _texture: NativeHandle,
  ): TextureCubeInfo { return this.unsupported("getTextureCubeInfo"); }
  public setTextureCubeColors(
    _texture: NativeHandle,
    _face: number,
    _level: number,
    _rectangle: {
    readonly X: number;
    readonly Y: number;
    readonly Width: number;
    readonly Height: number;
} | null,
    _startIndex: number,
    _elementCount: number,
    _packedColors: Uint32Array,
  ): void { return this.unsupported("setTextureCubeColors"); }
  public getTextureCubeColors(
    _texture: NativeHandle,
    _face: number,
    _level: number,
    _rectangle: {
    readonly X: number;
    readonly Y: number;
    readonly Width: number;
    readonly Height: number;
} | null,
    _startIndex: number,
    _elementCount: number,
    _capacity: number,
  ): Uint32Array { return this.unsupported("getTextureCubeColors"); }
  public destroyTextureCube(_texture: NativeHandle): void { return this.unsupported("destroyTextureCube"); }
  public createRenderTarget2D(
    _device: NativeHandle,
    _width: number,
    _height: number,
    _mipMap: boolean,
    _format: number,
    _depthFormat: number,
    _multiSampleCount: number,
    _usage: number,
  ): NativeHandle { return this.unsupported("createRenderTarget2D"); }
  public createRenderTargetCube(
    _device: NativeHandle,
    _size: number,
    _mipMap: boolean,
    _format: number,
    _depthFormat: number,
    _multiSampleCount: number,
    _usage: number,
  ): NativeHandle { return this.unsupported("createRenderTargetCube"); }
  public getRenderTargetInfo(
    _target: NativeHandle,
  ): RenderTargetInfo { return this.unsupported("getRenderTargetInfo"); }
  public destroyRenderTarget(_target: NativeHandle): void { return this.unsupported("destroyRenderTarget"); }
  public setGraphicsDeviceRenderTargets(
    _device: NativeHandle,
    _bindings: readonly RenderTargetBindingSnapshot[],
  ): void { return this.unsupported("setGraphicsDeviceRenderTargets"); }
  public createOcclusionQuery(
    _device: NativeHandle,
  ): NativeHandle { return this.unsupported("createOcclusionQuery"); }
  public beginOcclusionQuery(_query: NativeHandle): void { return this.unsupported("beginOcclusionQuery"); }
  public endOcclusionQuery(_query: NativeHandle): void { return this.unsupported("endOcclusionQuery"); }
  public getOcclusionQueryIsComplete(
    _query: NativeHandle,
  ): boolean { return this.unsupported("getOcclusionQueryIsComplete"); }
  public getOcclusionQueryPixelCount(
    _query: NativeHandle,
  ): number { return this.unsupported("getOcclusionQueryPixelCount"); }
  public destroyOcclusionQuery(
    _query: NativeHandle,
  ): void { return this.unsupported("destroyOcclusionQuery"); }
}

/** Refusing base for {@link CnaEffectBackend}. */
export abstract class CnaEffectBackendBase implements CnaEffectBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public createEffectEmpty(
    _device: NativeHandle,
  ): NativeHandle { return this.unsupported("createEffectEmpty"); }
  public createEffectCompiled(
    _device: NativeHandle,
    _bytes: Uint8Array,
  ): NativeHandle { return this.unsupported("createEffectCompiled"); }
  public cloneEffect(_effect: NativeHandle): NativeHandle { return this.unsupported("cloneEffect"); }
  public createStockEffect(
    _device: NativeHandle,
    _kind: number,
  ): NativeHandle { return this.unsupported("createStockEffect"); }
  public getEffectReflection(
    _effect: NativeHandle,
  ): NativeEffectReflectionSnapshot { return this.unsupported("getEffectReflection"); }
  public setEffectCurrentTechnique(
    _effect: NativeHandle,
    _technique: NativeHandle,
  ): void { return this.unsupported("setEffectCurrentTechnique"); }
  public applyEffect(_effect: NativeHandle): void { return this.unsupported("applyEffect"); }
  public applyEffectPass(_pass: NativeHandle): void { return this.unsupported("applyEffectPass"); }
  public syncStockEffect(
    _effect: NativeHandle,
    _kind: number,
    _snapshot: StockEffectSnapshot,
  ): void { return this.unsupported("syncStockEffect"); }
  public destroyEffectTechnique(
    _technique: NativeHandle,
  ): void { return this.unsupported("destroyEffectTechnique"); }
  public destroyEffectPass(_pass: NativeHandle): void { return this.unsupported("destroyEffectPass"); }
  public destroyEffect(_effect: NativeHandle): void { return this.unsupported("destroyEffect"); }
  public beginSpriteBatchWithEffect(
    _spriteBatch: NativeHandle,
    _sortMode: number,
    _blend: BlendStateSnapshot,
    _sampler: SamplerStateSnapshot,
    _depth: DepthStencilStateSnapshot,
    _rasterizer: RasterizerStateSnapshot,
    _effect: NativeHandle,
    _transform: readonly number[] | null,
  ): void { return this.unsupported("beginSpriteBatchWithEffect"); }
}

/** Refusing base for {@link CnaXactBackend}. */
export abstract class CnaXactBackendBase implements CnaXactBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public get ParentLifetime(): NativeResourceLifetime { return this.unsupported("ParentLifetime"); }
  public createAudioEngine(
    _settingsFile: string,
    _lookAheadTicks?: bigint,
    _rendererId?: string,
  ): NativeHandle { return this.unsupported("createAudioEngine"); }
  public destroyAudioEngine(_engine: NativeHandle): void { return this.unsupported("destroyAudioEngine"); }
  public getAudioEngineIsDisposed(
    _engine: NativeHandle,
  ): boolean { return this.unsupported("getAudioEngineIsDisposed"); }
  public getAudioEngineRendererDetails(
    _engine: NativeHandle,
  ): readonly RendererDetailSnapshot[] { return this.unsupported("getAudioEngineRendererDetails"); }
  public getAudioEngineGlobalVariable(
    _engine: NativeHandle,
    _name: string,
  ): number { return this.unsupported("getAudioEngineGlobalVariable"); }
  public setAudioEngineGlobalVariable(
    _engine: NativeHandle,
    _name: string,
    _value: number,
  ): void { return this.unsupported("setAudioEngineGlobalVariable"); }
  public updateAudioEngine(_engine: NativeHandle): void { return this.unsupported("updateAudioEngine"); }
  public getAudioCategory(
    _engine: NativeHandle,
    _name: string,
  ): NativeHandle { return this.unsupported("getAudioCategory"); }
  public destroyAudioCategory(
    _category: NativeHandle,
  ): void { return this.unsupported("destroyAudioCategory"); }
  public getAudioCategoryName(
    _category: NativeHandle,
  ): string { return this.unsupported("getAudioCategoryName"); }
  public pauseAudioCategory(_category: NativeHandle): void { return this.unsupported("pauseAudioCategory"); }
  public resumeAudioCategory(
    _category: NativeHandle,
  ): void { return this.unsupported("resumeAudioCategory"); }
  public setAudioCategoryVolume(
    _category: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setAudioCategoryVolume"); }
  public stopAudioCategory(
    _category: NativeHandle,
    _options: number,
  ): void { return this.unsupported("stopAudioCategory"); }
  public audioCategoriesEqual(
    _left: NativeHandle,
    _right: NativeHandle,
  ): boolean { return this.unsupported("audioCategoriesEqual"); }
  public getAudioCategoryHashCode(
    _category: NativeHandle,
  ): number { return this.unsupported("getAudioCategoryHashCode"); }
  public createSoundBank(
    _engine: NativeHandle,
    _filename: string,
  ): NativeHandle { return this.unsupported("createSoundBank"); }
  public destroySoundBank(_bank: NativeHandle): void { return this.unsupported("destroySoundBank"); }
  public getSoundBankIsDisposed(
    _bank: NativeHandle,
  ): boolean { return this.unsupported("getSoundBankIsDisposed"); }
  public getSoundBankIsInUse(_bank: NativeHandle): boolean { return this.unsupported("getSoundBankIsInUse"); }
  public getCue(_bank: NativeHandle, _name: string): NativeHandle { return this.unsupported("getCue"); }
  public playCue(_bank: NativeHandle, _name: string): void { return this.unsupported("playCue"); }
  public playCue3D(
    _bank: NativeHandle,
    _name: string,
    _listener: AudioListenerSnapshot,
    _emitter: AudioEmitterSnapshot,
  ): void { return this.unsupported("playCue3D"); }
  public createWaveBank(
    _engine: NativeHandle,
    _filename: string,
  ): NativeHandle { return this.unsupported("createWaveBank"); }
  public createStreamingWaveBank(
    _engine: NativeHandle,
    _filename: string,
    _offset: number,
    _packetSize: number,
  ): NativeHandle { return this.unsupported("createStreamingWaveBank"); }
  public destroyWaveBank(_bank: NativeHandle): void { return this.unsupported("destroyWaveBank"); }
  public getWaveBankIsDisposed(
    _bank: NativeHandle,
  ): boolean { return this.unsupported("getWaveBankIsDisposed"); }
  public getWaveBankIsInUse(_bank: NativeHandle): boolean { return this.unsupported("getWaveBankIsInUse"); }
  public getWaveBankIsPrepared(
    _bank: NativeHandle,
  ): boolean { return this.unsupported("getWaveBankIsPrepared"); }
  public destroyCue(_cue: NativeHandle): void { return this.unsupported("destroyCue"); }
  public getCueInfo(_cue: NativeHandle): CueSnapshot { return this.unsupported("getCueInfo"); }
  public getCueName(_cue: NativeHandle): string { return this.unsupported("getCueName"); }
  public applyCue3D(
    _cue: NativeHandle,
    _listener: AudioListenerSnapshot,
    _emitter: AudioEmitterSnapshot,
  ): void { return this.unsupported("applyCue3D"); }
  public getCueVariable(
    _cue: NativeHandle,
    _name: string,
  ): number { return this.unsupported("getCueVariable"); }
  public setCueVariable(
    _cue: NativeHandle,
    _name: string,
    _value: number,
  ): void { return this.unsupported("setCueVariable"); }
  public playCueHandle(_cue: NativeHandle): void { return this.unsupported("playCueHandle"); }
  public pauseCue(_cue: NativeHandle): void { return this.unsupported("pauseCue"); }
  public resumeCue(_cue: NativeHandle): void { return this.unsupported("resumeCue"); }
  public stopCue(_cue: NativeHandle, _options: number): void { return this.unsupported("stopCue"); }
}

/** Refusing base for {@link CnaMediaBackend}. */
export abstract class CnaMediaBackendBase implements CnaMediaBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public getAvailableMediaSources(
  ): readonly MediaSourceSnapshot[] { return this.unsupported("getAvailableMediaSources"); }
  public playSongs(
    _songs: readonly MediaSongPlaybackSnapshot[],
    _index: number,
  ): void { return this.unsupported("playSongs"); }
  public pause(): void { return this.unsupported("pause"); }
  public resume(): void { return this.unsupported("resume"); }
  public stop(): void { return this.unsupported("stop"); }
  public moveNext(): void { return this.unsupported("moveNext"); }
  public movePrevious(): void { return this.unsupported("movePrevious"); }
  public setVolume(_value: number): void { return this.unsupported("setVolume"); }
  public setMuted(_value: boolean): void { return this.unsupported("setMuted"); }
  public setRepeating(_value: boolean): void { return this.unsupported("setRepeating"); }
  public setShuffled(_value: boolean): void { return this.unsupported("setShuffled"); }
  public setVisualizationEnabled(
    _value: boolean,
  ): void { return this.unsupported("setVisualizationEnabled"); }
  public getGameHasControl(): boolean { return this.unsupported("getGameHasControl"); }
  public getPlayPositionTicks(): bigint { return this.unsupported("getPlayPositionTicks"); }
  public getVisualizationData(
  ): {
    readonly Frequencies: readonly number[];
    readonly Samples: readonly number[];
} { return this.unsupported("getVisualizationData"); }
  public update(): void { return this.unsupported("update"); }
}

/** Refusing base for {@link CnaVideoBackend}. */
export abstract class CnaVideoBackendBase implements CnaVideoBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public get ParentLifetime(): NativeResourceLifetime { return this.unsupported("ParentLifetime"); }
  public createVideoPlayer(): NativeHandle { return this.unsupported("createVideoPlayer"); }
  public destroyVideoPlayer(_player: NativeHandle): void { return this.unsupported("destroyVideoPlayer"); }
  public getVideoPlayerInfo(
    _player: NativeHandle,
  ): VideoPlayerSnapshot { return this.unsupported("getVideoPlayerInfo"); }
  public getVideoPlayerFrame(
    _player: NativeHandle,
  ): VideoFrameSnapshot { return this.unsupported("getVideoPlayerFrame"); }
  public setVideoPlayerLooped(
    _player: NativeHandle,
    _value: boolean,
  ): void { return this.unsupported("setVideoPlayerLooped"); }
  public setVideoPlayerMuted(
    _player: NativeHandle,
    _value: boolean,
  ): void { return this.unsupported("setVideoPlayerMuted"); }
  public setVideoPlayerVolume(
    _player: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setVideoPlayerVolume"); }
  public playVideo(
    _player: NativeHandle,
    _video: NativeHandle,
  ): void { return this.unsupported("playVideo"); }
  public pauseVideo(_player: NativeHandle): void { return this.unsupported("pauseVideo"); }
  public resumeVideo(_player: NativeHandle): void { return this.unsupported("resumeVideo"); }
  public stopVideo(_player: NativeHandle): void { return this.unsupported("stopVideo"); }
}

/** Refusing base for {@link CnaStorageBackend}. */
export abstract class CnaStorageBackendBase implements CnaStorageBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public get ParentLifetime(): NativeResourceLifetime { return this.unsupported("ParentLifetime"); }
  public selectStorageDevice(
    _player: number | null,
    _sizeInBytes: number | null,
    _directoryCount: number | null,
  ): NativeHandle { return this.unsupported("selectStorageDevice"); }
  public destroyStorageDevice(
    _device: NativeHandle,
  ): void { return this.unsupported("destroyStorageDevice"); }
  public getStorageDeviceInfo(
    _device: NativeHandle,
  ): StorageDeviceSnapshot { return this.unsupported("getStorageDeviceInfo"); }
  public deleteStorageContainer(
    _device: NativeHandle,
    _name: string,
  ): void { return this.unsupported("deleteStorageContainer"); }
  public openStorageContainer(
    _device: NativeHandle,
    _name: string,
  ): NativeHandle { return this.unsupported("openStorageContainer"); }
  public destroyStorageContainer(
    _container: NativeHandle,
  ): void { return this.unsupported("destroyStorageContainer"); }
  public getStorageContainerDisplayName(
    _container: NativeHandle,
  ): string { return this.unsupported("getStorageContainerDisplayName"); }
  public createStorageDirectory(
    _container: NativeHandle,
    _path: string,
  ): void { return this.unsupported("createStorageDirectory"); }
  public storageDirectoryExists(
    _container: NativeHandle,
    _path: string,
  ): boolean { return this.unsupported("storageDirectoryExists"); }
  public deleteStorageDirectory(
    _container: NativeHandle,
    _path: string,
  ): void { return this.unsupported("deleteStorageDirectory"); }
  public getStorageDirectoryNames(
    _container: NativeHandle,
    _pattern: string,
  ): readonly string[] { return this.unsupported("getStorageDirectoryNames"); }
  public createStorageFile(
    _container: NativeHandle,
    _path: string,
  ): void { return this.unsupported("createStorageFile"); }
  public storageFileExists(
    _container: NativeHandle,
    _path: string,
  ): boolean { return this.unsupported("storageFileExists"); }
  public deleteStorageFile(
    _container: NativeHandle,
    _path: string,
  ): void { return this.unsupported("deleteStorageFile"); }
  public getStorageFileNames(
    _container: NativeHandle,
    _pattern: string,
  ): readonly string[] { return this.unsupported("getStorageFileNames"); }
  public openStorageFile(
    _container: NativeHandle,
    _path: string,
    _mode: number,
    _access: number,
    _share: number,
  ): Uint8Array { return this.unsupported("openStorageFile"); }
}

/** Refusing base for {@link CnaAudioBackend}. */
export abstract class CnaAudioBackendBase implements CnaAudioBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public get ParentLifetime(): NativeResourceLifetime { return this.unsupported("ParentLifetime"); }
  public createSoundEffect(
    _pcmBytes: Uint8Array,
    _offset: number,
    _count: number,
    _sampleRate: number,
    _channels: number,
    _loopStart: number,
    _loopLength: number,
  ): NativeHandle { return this.unsupported("createSoundEffect"); }
  public createSoundEffectFromEncoded(
    _encoded: Uint8Array,
  ): NativeHandle { return this.unsupported("createSoundEffectFromEncoded"); }
  public getSoundEffectDurationTicks(
    _soundEffect: NativeHandle,
  ): bigint { return this.unsupported("getSoundEffectDurationTicks"); }
  public getSoundEffectName(
    _soundEffect: NativeHandle,
  ): string { return this.unsupported("getSoundEffectName"); }
  public setSoundEffectName(
    _soundEffect: NativeHandle,
    _value: string,
  ): void { return this.unsupported("setSoundEffectName"); }
  public createSoundEffectInstance(
    _soundEffect: NativeHandle,
  ): NativeHandle { return this.unsupported("createSoundEffectInstance"); }
  public playSoundEffect(
    _soundEffect: NativeHandle,
    _volume: number,
    _pitch: number,
    _pan: number,
  ): boolean { return this.unsupported("playSoundEffect"); }
  public destroySoundEffect(
    _soundEffect: NativeHandle,
  ): void { return this.unsupported("destroySoundEffect"); }
  public getMasterVolume(): number { return this.unsupported("getMasterVolume"); }
  public setMasterVolume(_value: number): void { return this.unsupported("setMasterVolume"); }
  public getDistanceScale(): number { return this.unsupported("getDistanceScale"); }
  public setDistanceScale(_value: number): void { return this.unsupported("setDistanceScale"); }
  public getDopplerScale(): number { return this.unsupported("getDopplerScale"); }
  public setDopplerScale(_value: number): void { return this.unsupported("setDopplerScale"); }
  public getSpeedOfSound(): number { return this.unsupported("getSpeedOfSound"); }
  public setSpeedOfSound(_value: number): void { return this.unsupported("setSpeedOfSound"); }
  public playSoundEffectInstance(
    _instance: NativeHandle,
  ): void { return this.unsupported("playSoundEffectInstance"); }
  public pauseSoundEffectInstance(
    _instance: NativeHandle,
  ): void { return this.unsupported("pauseSoundEffectInstance"); }
  public resumeSoundEffectInstance(
    _instance: NativeHandle,
  ): void { return this.unsupported("resumeSoundEffectInstance"); }
  public stopSoundEffectInstance(
    _instance: NativeHandle,
    _immediate: boolean,
  ): void { return this.unsupported("stopSoundEffectInstance"); }
  public getSoundEffectInstanceInfo(
    _instance: NativeHandle,
  ): SoundEffectInstanceSnapshot { return this.unsupported("getSoundEffectInstanceInfo"); }
  public setSoundEffectInstanceVolume(
    _instance: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSoundEffectInstanceVolume"); }
  public setSoundEffectInstancePitch(
    _instance: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSoundEffectInstancePitch"); }
  public setSoundEffectInstancePan(
    _instance: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSoundEffectInstancePan"); }
  public setSoundEffectInstanceLooped(
    _instance: NativeHandle,
    _value: boolean,
  ): void { return this.unsupported("setSoundEffectInstanceLooped"); }
  public applySoundEffectInstance3D(
    _instance: NativeHandle,
    _listeners: readonly AudioListenerSnapshot[],
    _emitter: AudioEmitterSnapshot,
  ): void { return this.unsupported("applySoundEffectInstance3D"); }
  public destroySoundEffectInstance(
    _instance: NativeHandle,
  ): void { return this.unsupported("destroySoundEffectInstance"); }
  public createDynamicSoundEffectInstance(
    _sampleRate: number,
    _channels: number,
  ): NativeHandle { return this.unsupported("createDynamicSoundEffectInstance"); }
  public getDynamicPendingBufferCount(
    _instance: NativeHandle,
  ): number { return this.unsupported("getDynamicPendingBufferCount"); }
  public submitDynamicBuffer(
    _instance: NativeHandle,
    _buffer: Uint8Array,
    _offset: number,
    _count: number,
  ): void { return this.unsupported("submitDynamicBuffer"); }
}

/** Refusing base for {@link CnaRuntimeServicesBackend}. */
export abstract class CnaRuntimeServicesBackendBase implements CnaRuntimeServicesBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public getPlatform(): PlatformSnapshot { return this.unsupported("getPlatform"); }
  public getRendererSelection(
  ): RendererSelectionSnapshot { return this.unsupported("getRendererSelection"); }
  public getAvailableRendererTypes(
  ): readonly number[] { return this.unsupported("getAvailableRendererTypes"); }
  public isRendererAvailable(_type: number): boolean { return this.unsupported("isRendererAvailable"); }
  public describeRenderer(
    _type: number,
  ): RendererIdentitySnapshot { return this.unsupported("describeRenderer"); }
  public setPreferredRenderer(_type: number): void { return this.unsupported("setPreferredRenderer"); }
  public setPreferredRendererByName(
    _name: string,
  ): void { return this.unsupported("setPreferredRendererByName"); }
  public tryParseRendererName(
    _name: string,
  ): number | null { return this.unsupported("tryParseRendererName"); }
  public setRendererFallbackChain(
    _types: readonly number[],
  ): void { return this.unsupported("setRendererFallbackChain"); }
  public setAutomaticRendererFallback(
    _enabled: boolean,
  ): void { return this.unsupported("setAutomaticRendererFallback"); }
  public getRendererFallbacks(
  ): readonly RendererFallbackSnapshot[] { return this.unsupported("getRendererFallbacks"); }
  public getMinimumLogLevel(): number { return this.unsupported("getMinimumLogLevel"); }
  public setMinimumLogLevel(_level: number): void { return this.unsupported("setMinimumLogLevel"); }
  public writeLog(
    _level: number,
    _category: number,
    _message: string,
  ): void { return this.unsupported("writeLog"); }
  public isGraphicsExtensionLayerAvailable(
  ): boolean { return this.unsupported("isGraphicsExtensionLayerAvailable"); }
}

/** Refusing base for {@link CnaGraphicsExtensionBackend}. */
export abstract class CnaGraphicsExtensionBackendBase implements CnaGraphicsExtensionBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public getDefaultPbrMaterial(): PbrMaterialDefaults { return this.unsupported("getDefaultPbrMaterial"); }
  public getDefaultRenderPipelineSettings(
  ): RenderPipelineSettingsDefaults { return this.unsupported("getDefaultRenderPipelineSettings"); }
  public createRenderPipeline(
    _device: NativeHandle,
  ): NativeHandle { return this.unsupported("createRenderPipeline"); }
  public destroyRenderPipeline(
    _pipeline: NativeHandle,
  ): void { return this.unsupported("destroyRenderPipeline"); }
  public resizeRenderPipeline(
    _pipeline: NativeHandle,
    _width: number,
    _height: number,
  ): void { return this.unsupported("resizeRenderPipeline"); }
  public beginRenderPipeline(
    _pipeline: NativeHandle,
    _packedClearColor: number,
  ): void { return this.unsupported("beginRenderPipeline"); }
  public endRenderPipeline(_pipeline: NativeHandle): void { return this.unsupported("endRenderPipeline"); }
  public getRenderPipelineStatistics(
    _pipeline: NativeHandle,
  ): RenderPipelineStatisticsSnapshot { return this.unsupported("getRenderPipelineStatistics"); }
  public createBlitPass(_device: NativeHandle): NativeHandle { return this.unsupported("createBlitPass"); }
  public createBloomPass(_device: NativeHandle): NativeHandle { return this.unsupported("createBloomPass"); }
  public createTonemapPass(
    _device: NativeHandle,
  ): NativeHandle { return this.unsupported("createTonemapPass"); }
  public createFxaaPass(_device: NativeHandle): NativeHandle { return this.unsupported("createFxaaPass"); }
  public createSsaoPass(_device: NativeHandle): NativeHandle { return this.unsupported("createSsaoPass"); }
  public createSsrPass(_device: NativeHandle): NativeHandle { return this.unsupported("createSsrPass"); }
  public getBloomIntensity(_pass: NativeHandle): number { return this.unsupported("getBloomIntensity"); }
  public setBloomIntensity(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setBloomIntensity"); }
  public getBloomThreshold(_pass: NativeHandle): number { return this.unsupported("getBloomThreshold"); }
  public setBloomThreshold(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setBloomThreshold"); }
  public getTonemapExposure(_pass: NativeHandle): number { return this.unsupported("getTonemapExposure"); }
  public setTonemapExposure(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setTonemapExposure"); }
  public getTonemapGamma(_pass: NativeHandle): number { return this.unsupported("getTonemapGamma"); }
  public setTonemapGamma(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setTonemapGamma"); }
  public getTonemapDebandStrength(
    _pass: NativeHandle,
  ): number { return this.unsupported("getTonemapDebandStrength"); }
  public setTonemapDebandStrength(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setTonemapDebandStrength"); }
  public getFxaaEdgeThreshold(
    _pass: NativeHandle,
  ): number { return this.unsupported("getFxaaEdgeThreshold"); }
  public setFxaaEdgeThreshold(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setFxaaEdgeThreshold"); }
  public getSsaoRadius(_pass: NativeHandle): number { return this.unsupported("getSsaoRadius"); }
  public setSsaoRadius(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsaoRadius"); }
  public getSsaoIntensity(_pass: NativeHandle): number { return this.unsupported("getSsaoIntensity"); }
  public setSsaoIntensity(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsaoIntensity"); }
  public getSsrIntensity(_pass: NativeHandle): number { return this.unsupported("getSsrIntensity"); }
  public setSsrIntensity(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsrIntensity"); }
  public getSsrMaxDistance(_pass: NativeHandle): number { return this.unsupported("getSsrMaxDistance"); }
  public setSsrMaxDistance(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsrMaxDistance"); }
  public getSsrThickness(_pass: NativeHandle): number { return this.unsupported("getSsrThickness"); }
  public setSsrThickness(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsrThickness"); }
  public getSsrDepthBias(_pass: NativeHandle): number { return this.unsupported("getSsrDepthBias"); }
  public setSsrDepthBias(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsrDepthBias"); }
  public getSsrEdgeFade(_pass: NativeHandle): number { return this.unsupported("getSsrEdgeFade"); }
  public setSsrEdgeFade(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsrEdgeFade"); }
  public getSsrRoughnessBlur(_pass: NativeHandle): number { return this.unsupported("getSsrRoughnessBlur"); }
  public setSsrRoughnessBlur(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsrRoughnessBlur"); }
  public getBloomIterations(_pass: NativeHandle): number { return this.unsupported("getBloomIterations"); }
  public setBloomIterations(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setBloomIterations"); }
  public getSsaoSampleCount(_pass: NativeHandle): number { return this.unsupported("getSsaoSampleCount"); }
  public setSsaoSampleCount(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsaoSampleCount"); }
  public getSsrStepCount(_pass: NativeHandle): number { return this.unsupported("getSsrStepCount"); }
  public setSsrStepCount(
    _pass: NativeHandle,
    _value: number,
  ): void { return this.unsupported("setSsrStepCount"); }
  public getSsaoHalfResolution(
    _pass: NativeHandle,
  ): boolean { return this.unsupported("getSsaoHalfResolution"); }
  public setSsaoHalfResolution(
    _pass: NativeHandle,
    _value: boolean,
  ): void { return this.unsupported("setSsaoHalfResolution"); }
  public getTonemapMode(_pass: NativeHandle): number { return this.unsupported("getTonemapMode"); }
  public setTonemapMode(
    _pass: NativeHandle,
    _mode: number,
  ): void { return this.unsupported("setTonemapMode"); }
  public getTonemapDebandEnabled(
    _pass: NativeHandle,
  ): boolean { return this.unsupported("getTonemapDebandEnabled"); }
  public setTonemapDebandEnabled(
    _pass: NativeHandle,
    _value: boolean,
  ): void { return this.unsupported("setTonemapDebandEnabled"); }
  public bloomIterationsForQuality(
    _quality: number,
  ): number { return this.unsupported("bloomIterationsForQuality"); }
  public ssaoSampleCountForQuality(
    _quality: number,
  ): number { return this.unsupported("ssaoSampleCountForQuality"); }
  public fxaaEdgeThresholdForQuality(
    _quality: number,
  ): number { return this.unsupported("fxaaEdgeThresholdForQuality"); }
  public resetBloomTargets(_pass: NativeHandle): void { return this.unsupported("resetBloomTargets"); }
  public resetSsaoTargets(_pass: NativeHandle): void { return this.unsupported("resetSsaoTargets"); }
  public applyPostProcessPass(
    _pass: NativeHandle,
    _frame: PostProcessFrameSnapshot,
  ): void { return this.unsupported("applyPostProcessPass"); }
  public getPostProcessPassName(
    _pass: NativeHandle,
  ): string { return this.unsupported("getPostProcessPassName"); }
  public isPostProcessPassSupported(
    _pass: NativeHandle,
    _device: NativeHandle,
  ): boolean { return this.unsupported("isPostProcessPassSupported"); }
  public destroyPostProcessPass(
    _pass: NativeHandle,
  ): void { return this.unsupported("destroyPostProcessPass"); }
  public createPostProcessChain(
    _device: NativeHandle,
  ): NativeHandle { return this.unsupported("createPostProcessChain"); }
  public destroyPostProcessChain(
    _chain: NativeHandle,
  ): void { return this.unsupported("destroyPostProcessChain"); }
  public clearPostProcessChain(
    _chain: NativeHandle,
  ): void { return this.unsupported("clearPostProcessChain"); }
  public resetPostProcessChainTargets(
    _chain: NativeHandle,
  ): void { return this.unsupported("resetPostProcessChainTargets"); }
  public addPostProcessPass(
    _chain: NativeHandle,
    _pass: NativeHandle,
  ): void { return this.unsupported("addPostProcessPass"); }
  public addOwnedPostProcessPass(
    _chain: NativeHandle,
    _pass: NativeHandle,
  ): void { return this.unsupported("addOwnedPostProcessPass"); }
  public getPostProcessChainPassCount(
    _chain: NativeHandle,
  ): number { return this.unsupported("getPostProcessChainPassCount"); }
  public getPostProcessChainGpuTimingEnabled(
    _chain: NativeHandle,
  ): boolean { return this.unsupported("getPostProcessChainGpuTimingEnabled"); }
  public setPostProcessChainGpuTimingEnabled(
    _chain: NativeHandle,
    _value: boolean,
  ): void { return this.unsupported("setPostProcessChainGpuTimingEnabled"); }
  public applyPostProcessChain(
    _chain: NativeHandle,
    _frame: PostProcessFrameSnapshot,
  ): void { return this.unsupported("applyPostProcessChain"); }
  public getPostProcessChainPassTimings(
    _chain: NativeHandle,
  ): readonly PassTimingSnapshot[] { return this.unsupported("getPostProcessChainPassTimings"); }
}

/** Refusing base for {@link CnaExtendedInputBackend}. */
export abstract class CnaExtendedInputBackendBase implements CnaExtendedInputBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public getJoystickCount(): number { return this.unsupported("getJoystickCount"); }
  public getJoystickInfoAt(
    _index: number,
  ): JoystickInfoSnapshot { return this.unsupported("getJoystickInfoAt"); }
  public getJoystickNameAt(_index: number): string { return this.unsupported("getJoystickNameAt"); }
  public getJoystickCapabilities(
    _id: number,
  ): JoystickCapabilitiesSnapshot { return this.unsupported("getJoystickCapabilities"); }
  public getJoystickCapabilitiesName(
    _id: number,
  ): string { return this.unsupported("getJoystickCapabilitiesName"); }
  public getJoystickCapabilitiesGuid(
    _id: number,
  ): string { return this.unsupported("getJoystickCapabilitiesGuid"); }
  public captureJoystickState(
    _id: number,
  ): JoystickStateSnapshot { return this.unsupported("captureJoystickState"); }
  public getHapticCount(): number { return this.unsupported("getHapticCount"); }
  public getHapticIdAt(_index: number): number { return this.unsupported("getHapticIdAt"); }
  public getHapticNameAt(_index: number): string { return this.unsupported("getHapticNameAt"); }
  public isJoystickHaptic(_joystickId: number): boolean { return this.unsupported("isJoystickHaptic"); }
  public openHaptic(_id: number): NativeHandle { return this.unsupported("openHaptic"); }
  public openHapticFromJoystick(
    _joystickId: number,
  ): NativeHandle { return this.unsupported("openHapticFromJoystick"); }
  public getHapticCapabilities(
    _device: NativeHandle,
  ): HapticCapabilitiesSnapshot { return this.unsupported("getHapticCapabilities"); }
  public getHapticName(_device: NativeHandle): string { return this.unsupported("getHapticName"); }
  public getHapticIsOpen(_device: NativeHandle): boolean { return this.unsupported("getHapticIsOpen"); }
  public initHapticRumble(_device: NativeHandle): boolean { return this.unsupported("initHapticRumble"); }
  public playHapticRumble(
    _device: NativeHandle,
    _strength: number,
    _lengthMilliseconds: number,
  ): boolean { return this.unsupported("playHapticRumble"); }
  public stopHapticRumble(_device: NativeHandle): boolean { return this.unsupported("stopHapticRumble"); }
  public setHapticGain(
    _device: NativeHandle,
    _gain: number,
  ): boolean { return this.unsupported("setHapticGain"); }
  public disposeHapticDevice(_device: NativeHandle): void { return this.unsupported("disposeHapticDevice"); }
  public destroyHapticDevice(_device: NativeHandle): void { return this.unsupported("destroyHapticDevice"); }
}

/** Refusing base for {@link CnaContentBackend}. */
export abstract class CnaContentBackendBase implements CnaContentBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public cnbHasMagic(_bytes: Uint8Array): boolean { return this.unsupported("cnbHasMagic"); }
  public cnbFormatMagic(): Uint8Array { return this.unsupported("cnbFormatMagic"); }
  public cnbCrc32c(_bytes: Uint8Array): number { return this.unsupported("cnbCrc32c"); }
  public cnbIsCompressionSupported(
    _codec: number,
  ): boolean { return this.unsupported("cnbIsCompressionSupported"); }
  public cnbCompressionName(_codec: number): string { return this.unsupported("cnbCompressionName"); }
  public cnbAssetTypeName(_assetTypeId: number): string { return this.unsupported("cnbAssetTypeName"); }
  public cnbAssetTypeIdFromName(_name: string): number { return this.unsupported("cnbAssetTypeIdFromName"); }
  public cnbIsCustomAssetTypeId(
    _assetTypeId: number,
  ): boolean { return this.unsupported("cnbIsCustomAssetTypeId"); }
  public cnbMakeChunkId(
    _a: number,
    _b: number,
    _c: number,
    _d: number,
  ): number { return this.unsupported("cnbMakeChunkId"); }
  public cnbChunkIdString(_id: number): string { return this.unsupported("cnbChunkIdString"); }
  public cnbIsWellFormedChunkId(_id: number): boolean { return this.unsupported("cnbIsWellFormedChunkId"); }
  public cnbTextureFormatName(_format: number): string { return this.unsupported("cnbTextureFormatName"); }
  public cnbIsBlockCompressedTextureFormat(
    _format: number,
  ): boolean { return this.unsupported("cnbIsBlockCompressedTextureFormat"); }
  public cnbTextureFormatUnitBytes(
    _format: number,
  ): number { return this.unsupported("cnbTextureFormatUnitBytes"); }
  public cnbTextureLevelByteSize(
    _format: number,
    _width: number,
    _height: number,
    _depth: number,
  ): number { return this.unsupported("cnbTextureLevelByteSize"); }
  public cnbTextureFormatToSurfaceFormat(
    _format: number,
  ): number { return this.unsupported("cnbTextureFormatToSurfaceFormat"); }
  public cnbDocumentParse(
    _bytes: Uint8Array,
    _origin: string,
  ): NativeHandle { return this.unsupported("cnbDocumentParse"); }
  public cnbDocumentDestroy(_document: NativeHandle): void { return this.unsupported("cnbDocumentDestroy"); }
  public cnbDocumentGetInfo(
    _document: NativeHandle,
  ): CnbDocumentSnapshot { return this.unsupported("cnbDocumentGetInfo"); }
  public cnbDocumentGetChunk(
    _document: NativeHandle,
    _index: number,
  ): CnbChunkEntrySnapshot { return this.unsupported("cnbDocumentGetChunk"); }
  public cnbDocumentCopyChunkData(
    _document: NativeHandle,
    _index: number,
  ): Uint8Array { return this.unsupported("cnbDocumentCopyChunkData"); }
  public cnbDocumentFindAll(
    _document: NativeHandle,
    _type: number,
  ): readonly number[] { return this.unsupported("cnbDocumentFindAll"); }
  public cnbDocumentRequireMandatoryChunksUnderstood(
    _document: NativeHandle,
    _known: readonly number[],
  ): void { return this.unsupported("cnbDocumentRequireMandatoryChunksUnderstood"); }
  public cnbDocumentGetExternalReference(
    _document: NativeHandle,
    _index: number,
  ): CnbExternalReferenceSnapshot { return this.unsupported("cnbDocumentGetExternalReference"); }
  public cnbDecodeTexture2D(
    _document: NativeHandle,
  ): NativeHandle { return this.unsupported("cnbDecodeTexture2D"); }
  public cnbTextureDataDestroy(
    _texture: NativeHandle,
  ): void { return this.unsupported("cnbTextureDataDestroy"); }
  public cnbTextureDataGetInfo(
    _texture: NativeHandle,
  ): CnbTextureInfoSnapshot { return this.unsupported("cnbTextureDataGetInfo"); }
  public cnbTextureDataGetLevelDimensions(
    _texture: NativeHandle,
    _level: number,
  ): {
    readonly Width: number;
    readonly Height: number;
    readonly Depth: number;
} { return this.unsupported("cnbTextureDataGetLevelDimensions"); }
  public cnbTextureDataGetRepresentationFormat(
    _texture: NativeHandle,
    _representation: number,
  ): number { return this.unsupported("cnbTextureDataGetRepresentationFormat"); }
  public cnbTextureDataGetLevelCount(
    _texture: NativeHandle,
    _representation: number,
  ): number { return this.unsupported("cnbTextureDataGetLevelCount"); }
  public cnbTextureDataCopyLevel(
    _texture: NativeHandle,
    _representation: number,
    _level: number,
  ): Uint8Array { return this.unsupported("cnbTextureDataCopyLevel"); }
  public cnbTextureDataCreate(
    _width: number,
    _height: number,
    _depth: number,
    _faceCount: number,
    _mipCount: number,
  ): NativeHandle { return this.unsupported("cnbTextureDataCreate"); }
  public cnbTextureDataCreateRgba8(
    _width: number,
    _height: number,
    _rgba: Uint8Array,
  ): NativeHandle { return this.unsupported("cnbTextureDataCreateRgba8"); }
  public cnbTextureDataAddRepresentation(
    _texture: NativeHandle,
    _format: number,
  ): number { return this.unsupported("cnbTextureDataAddRepresentation"); }
  public cnbTextureDataSetLevel(
    _texture: NativeHandle,
    _representation: number,
    _level: number,
    _bytes: Uint8Array,
  ): void { return this.unsupported("cnbTextureDataSetLevel"); }
  public cnbEncodeTexture2D(
    _texture: NativeHandle,
    _contentName: string,
  ): Uint8Array { return this.unsupported("cnbEncodeTexture2D"); }
  public cnbDecodeSpriteFont(
    _document: NativeHandle,
  ): NativeHandle { return this.unsupported("cnbDecodeSpriteFont"); }
  public cnbSpriteFontDataCreate(): NativeHandle { return this.unsupported("cnbSpriteFontDataCreate"); }
  public cnbSpriteFontDataDestroy(
    _font: NativeHandle,
  ): void { return this.unsupported("cnbSpriteFontDataDestroy"); }
  public cnbSpriteFontDataGetInfo(
    _font: NativeHandle,
  ): CnbSpriteFontInfoSnapshot { return this.unsupported("cnbSpriteFontDataGetInfo"); }
  public cnbSpriteFontDataSetInfo(
    _font: NativeHandle,
    _info: {
    readonly LineSpacing: number;
    readonly Spacing: number;
    readonly DefaultCharacter: number;
    readonly HasDefaultCharacter: boolean;
},
  ): void { return this.unsupported("cnbSpriteFontDataSetInfo"); }
  public cnbSpriteFontDataGetGlyph(
    _font: NativeHandle,
    _index: number,
  ): CnbGlyphSnapshot { return this.unsupported("cnbSpriteFontDataGetGlyph"); }
  public cnbSpriteFontDataAddGlyph(
    _font: NativeHandle,
    _glyph: CnbGlyphSnapshot,
  ): number { return this.unsupported("cnbSpriteFontDataAddGlyph"); }
  public cnbSpriteFontDataSetAtlas(
    _font: NativeHandle,
    _atlas: NativeHandle,
  ): void { return this.unsupported("cnbSpriteFontDataSetAtlas"); }
  public cnbSpriteFontDataCopyAtlas(
    _font: NativeHandle,
  ): NativeHandle { return this.unsupported("cnbSpriteFontDataCopyAtlas"); }
  public cnbEncodeSpriteFont(
    _font: NativeHandle,
    _contentName: string,
  ): Uint8Array { return this.unsupported("cnbEncodeSpriteFont"); }
  public cnbEncodeCurve(
    _curve: CnbCurveSnapshot,
    _contentName: string,
  ): Uint8Array { return this.unsupported("cnbEncodeCurve"); }
  public cnbDecodeCurve(
    _document: NativeHandle,
  ): CnbCurveSnapshot { return this.unsupported("cnbDecodeCurve"); }
  public cnbEncodeAnimationClip(
    _durationSeconds: number,
    _tracks: readonly {
    readonly BoneIndex: number;
    readonly Keyframes: readonly CnbKeyframeSnapshot[];
}[],
    _targetSpace: number,
    _contentName: string,
  ): Uint8Array { return this.unsupported("cnbEncodeAnimationClip"); }
  public cnbDecodeAnimationClip(
    _document: NativeHandle,
  ): NativeHandle { return this.unsupported("cnbDecodeAnimationClip"); }
  public cnbAnimationClipDestroy(
    _clip: NativeHandle,
  ): void { return this.unsupported("cnbAnimationClipDestroy"); }
  public cnbAnimationClipGet(
    _clip: NativeHandle,
  ): {
    readonly DurationSeconds: number;
    readonly TrackCount: number;
    readonly TargetSpace: number;
} { return this.unsupported("cnbAnimationClipGet"); }
  public cnbAnimationClipGetTrack(
    _clip: NativeHandle,
    _track: number,
  ): {
    readonly BoneIndex: number;
    readonly KeyframeCount: number;
} { return this.unsupported("cnbAnimationClipGetTrack"); }
  public cnbAnimationClipCopyKeyframes(
    _clip: NativeHandle,
    _track: number,
  ): readonly CnbKeyframeSnapshot[] { return this.unsupported("cnbAnimationClipCopyKeyframes"); }
  public cnbSoundEffectDataCreate(
    _info: CnbSoundEffectInfoSnapshot,
    _samples: Uint8Array,
  ): NativeHandle { return this.unsupported("cnbSoundEffectDataCreate"); }
  public cnbSoundEffectDataDestroy(
    _sound: NativeHandle,
  ): void { return this.unsupported("cnbSoundEffectDataDestroy"); }
  public cnbSoundEffectDataGetInfo(
    _sound: NativeHandle,
  ): CnbSoundEffectInfoSnapshot { return this.unsupported("cnbSoundEffectDataGetInfo"); }
  public cnbSoundEffectDataCopySamples(
    _sound: NativeHandle,
  ): Uint8Array { return this.unsupported("cnbSoundEffectDataCopySamples"); }
  public cnbEncodeSoundEffect(
    _sound: NativeHandle,
    _contentName: string,
  ): Uint8Array { return this.unsupported("cnbEncodeSoundEffect"); }
  public cnbDecodeSoundEffect(
    _document: NativeHandle,
  ): NativeHandle { return this.unsupported("cnbDecodeSoundEffect"); }
  public cnbDecodeWavAsSoundEffect(
    _bytes: Uint8Array,
    _origin: string,
  ): NativeHandle { return this.unsupported("cnbDecodeWavAsSoundEffect"); }
  public cnbEncodeSong(
    _streamReference: string,
    _name: string,
    _durationMilliseconds: number,
    _contentName: string,
  ): Uint8Array { return this.unsupported("cnbEncodeSong"); }
  public cnbDecodeSongDuration(
    _document: NativeHandle,
  ): number { return this.unsupported("cnbDecodeSongDuration"); }
  public cnbDecodeSongName(_document: NativeHandle): string { return this.unsupported("cnbDecodeSongName"); }
  public cnbDecodeSongStreamReference(
    _document: NativeHandle,
  ): string { return this.unsupported("cnbDecodeSongStreamReference"); }
  public cnbEncodeVideo(
    _streamReference: string,
    _info: CnbVideoInfoSnapshot,
    _contentName: string,
  ): Uint8Array { return this.unsupported("cnbEncodeVideo"); }
  public cnbDecodeVideo(
    _document: NativeHandle,
  ): CnbVideoInfoSnapshot { return this.unsupported("cnbDecodeVideo"); }
  public cnbDecodeVideoStreamReference(
    _document: NativeHandle,
  ): string { return this.unsupported("cnbDecodeVideoStreamReference"); }
  public cnbModelCreate(): NativeHandle { return this.unsupported("cnbModelCreate"); }
  public cnbModelDestroy(_model: NativeHandle): void { return this.unsupported("cnbModelDestroy"); }
  public cnbModelSetFlags(
    _model: NativeHandle,
    _appliesGltfLightingPolicy: boolean,
    _hasBoneHierarchy: boolean,
  ): void { return this.unsupported("cnbModelSetFlags"); }
  public cnbModelGetInfo(
    _model: NativeHandle,
  ): CnbModelInfoSnapshot { return this.unsupported("cnbModelGetInfo"); }
  public cnbModelAddBone(
    _model: NativeHandle,
    _name: string,
    _parent: number,
    _transform: readonly number[],
  ): number { return this.unsupported("cnbModelAddBone"); }
  public cnbModelGetBone(
    _model: NativeHandle,
    _index: number,
  ): {
    readonly Parent: number;
    readonly Transform: readonly number[];
} { return this.unsupported("cnbModelGetBone"); }
  public cnbModelGetBoneName(
    _model: NativeHandle,
    _index: number,
  ): string { return this.unsupported("cnbModelGetBoneName"); }
  public cnbModelAddPart(
    _model: NativeHandle,
    _info: CnbModelPartSnapshot,
    _name: string,
    _externalEffect: string,
  ): number { return this.unsupported("cnbModelAddPart"); }
  public cnbModelGetPart(
    _model: NativeHandle,
    _index: number,
  ): CnbModelPartSnapshot { return this.unsupported("cnbModelGetPart"); }
  public cnbModelGetPartName(
    _model: NativeHandle,
    _index: number,
  ): string { return this.unsupported("cnbModelGetPartName"); }
  public cnbModelGetPartExternalEffect(
    _model: NativeHandle,
    _index: number,
  ): string { return this.unsupported("cnbModelGetPartExternalEffect"); }
  public cnbModelSetPartVertexBytes(
    _model: NativeHandle,
    _index: number,
    _bytes: Uint8Array,
  ): void { return this.unsupported("cnbModelSetPartVertexBytes"); }
  public cnbModelCopyPartVertexBytes(
    _model: NativeHandle,
    _index: number,
  ): Uint8Array { return this.unsupported("cnbModelCopyPartVertexBytes"); }
  public cnbModelSetPartIndexBytes(
    _model: NativeHandle,
    _index: number,
    _bytes: Uint8Array,
  ): void { return this.unsupported("cnbModelSetPartIndexBytes"); }
  public cnbModelCopyPartIndexBytes(
    _model: NativeHandle,
    _index: number,
  ): Uint8Array { return this.unsupported("cnbModelCopyPartIndexBytes"); }
  public cnbModelGetMaterial(
    _model: NativeHandle,
    _part: number,
  ): CnbMaterialSnapshot { return this.unsupported("cnbModelGetMaterial"); }
  public cnbModelSetMaterial(
    _model: NativeHandle,
    _part: number,
    _material: CnbMaterialSnapshot,
  ): void { return this.unsupported("cnbModelSetMaterial"); }
  public cnbModelGetMaterialTexture(
    _model: NativeHandle,
    _part: number,
    _slot: number,
  ): string { return this.unsupported("cnbModelGetMaterialTexture"); }
  public cnbModelSetMaterialTexture(
    _model: NativeHandle,
    _part: number,
    _slot: number,
    _assetName: string,
  ): void { return this.unsupported("cnbModelSetMaterialTexture"); }
  public cnbModelAddMesh(
    _model: NativeHandle,
    _name: string,
    _parentBone: number,
    _partIndices: readonly number[],
  ): number { return this.unsupported("cnbModelAddMesh"); }
  public cnbModelGetMesh(
    _model: NativeHandle,
    _index: number,
  ): {
    readonly ParentBone: number;
    readonly PartIndexCount: number;
} { return this.unsupported("cnbModelGetMesh"); }
  public cnbModelGetMeshName(
    _model: NativeHandle,
    _index: number,
  ): string { return this.unsupported("cnbModelGetMeshName"); }
  public cnbModelCopyMeshPartIndices(
    _model: NativeHandle,
    _index: number,
  ): readonly number[] { return this.unsupported("cnbModelCopyMeshPartIndices"); }
  public cnbModelSetSkeleton(
    _model: NativeHandle,
    _hierarchy: readonly number[],
    _bindPose: readonly number[],
    _inverseBindPose: readonly number[],
    _rootPrefix: readonly number[],
  ): void { return this.unsupported("cnbModelSetSkeleton"); }
  public cnbModelGetSkeleton(
    _model: NativeHandle,
  ): {
    readonly JointCount: number;
    readonly HasRootPrefix: boolean;
} { return this.unsupported("cnbModelGetSkeleton"); }
  public cnbModelCopySkeletonHierarchy(
    _model: NativeHandle,
  ): readonly number[] { return this.unsupported("cnbModelCopySkeletonHierarchy"); }
  public cnbModelCopySkeletonMatrices(
    _model: NativeHandle,
    _set: number,
  ): readonly number[] { return this.unsupported("cnbModelCopySkeletonMatrices"); }
  public cnbModelAddLight(
    _model: NativeHandle,
    _direction: readonly number[],
    _diffuseColor: readonly number[],
  ): number { return this.unsupported("cnbModelAddLight"); }
  public cnbModelGetLight(
    _model: NativeHandle,
    _index: number,
  ): {
    readonly Direction: readonly number[];
    readonly DiffuseColor: readonly number[];
} { return this.unsupported("cnbModelGetLight"); }
  public cnbEncodeModel(
    _model: NativeHandle,
    _contentName: string,
  ): Uint8Array { return this.unsupported("cnbEncodeModel"); }
  public cnbDecodeModel(_document: NativeHandle): NativeHandle { return this.unsupported("cnbDecodeModel"); }
}

/** Refusing base for {@link CnaDeviceBackend}. */
export abstract class CnaDeviceBackendBase implements CnaDeviceBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public isDeviceExtensionLayerAvailable(
  ): boolean { return this.unsupported("isDeviceExtensionLayerAvailable"); }
  public getHostDeviceInfo(): HostDeviceSnapshot { return this.unsupported("getHostDeviceInfo"); }
  public getPreferredLocales(
  ): readonly PreferredLocaleSnapshot[] { return this.unsupported("getPreferredLocales"); }
  public setClipboardText(_text: string): boolean { return this.unsupported("setClipboardText"); }
  public getCameras(): CameraInventorySnapshot { return this.unsupported("getCameras"); }
}

/** Refusing base for {@link CnaGamerServicesBackend}. */
export abstract class CnaGamerServicesBackendBase implements CnaGamerServicesBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public initializeGamerServices(): void { return this.unsupported("initializeGamerServices"); }
  public getGamerServicesIsInitialized(
  ): boolean { return this.unsupported("getGamerServicesIsInitialized"); }
  public updateGamerServices(): void { return this.unsupported("updateGamerServices"); }
  public getGamerServicesWindowHandle(): bigint { return this.unsupported("getGamerServicesWindowHandle"); }
  public setGamerServicesWindowHandle(
    _handle: bigint,
  ): void { return this.unsupported("setGamerServicesWindowHandle"); }
  public getGuideIsVisible(): boolean { return this.unsupported("getGuideIsVisible"); }
  public getGuideIsTrialMode(): boolean { return this.unsupported("getGuideIsTrialMode"); }
  public getGuideSimulateTrialMode(): boolean { return this.unsupported("getGuideSimulateTrialMode"); }
  public setGuideSimulateTrialMode(
    _value: boolean,
  ): void { return this.unsupported("setGuideSimulateTrialMode"); }
  public getGuideIsScreenSaverEnabled(): boolean { return this.unsupported("getGuideIsScreenSaverEnabled"); }
  public setGuideIsScreenSaverEnabled(
    _value: boolean,
  ): void { return this.unsupported("setGuideIsScreenSaverEnabled"); }
  public getGuideNotificationPosition(): number { return this.unsupported("getGuideNotificationPosition"); }
  public setGuideNotificationPosition(
    _position: number,
  ): void { return this.unsupported("setGuideNotificationPosition"); }
}

/** Refusing base for {@link CnaSensorBackend}. */
export abstract class CnaSensorBackendBase implements CnaSensorBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public getSensorSupport(): SensorSupportSnapshot { return this.unsupported("getSensorSupport"); }
  public createAccelerometer(): NativeHandle { return this.unsupported("createAccelerometer"); }
  public destroyAccelerometer(
    _sensor: NativeHandle,
  ): void { return this.unsupported("destroyAccelerometer"); }
  public startAccelerometer(_sensor: NativeHandle): void { return this.unsupported("startAccelerometer"); }
  public stopAccelerometer(_sensor: NativeHandle): void { return this.unsupported("stopAccelerometer"); }
  public getAccelerometerState(
    _sensor: NativeHandle,
  ): SensorStateSnapshot { return this.unsupported("getAccelerometerState"); }
  public setAccelerometerInterval(
    _sensor: NativeHandle,
    _ticks: bigint,
  ): void { return this.unsupported("setAccelerometerInterval"); }
  public getAccelerometerReading(
    _sensor: NativeHandle,
  ): AccelerometerReadingSnapshot { return this.unsupported("getAccelerometerReading"); }
}

/** Refusing base for {@link CnaBackend}. */
export abstract class CnaBackendBase implements CnaBackend {
  /** Refuses one member of this boundary, naming it. */
  protected abstract unsupported(member: string): never;
  public abstract readonly Kind: BackendKind;
  public abstract readonly IsAvailable: boolean;
  public abstract readonly AbiVersion: string | null;
  public abstract readonly Detail: string;
  public initialize(
  ): Promise<void> { try { return this.unsupported("initialize"); } catch (error) { return Promise.reject(error) as Promise<void>; } }
  public updateFrameworkDispatcher(): void { return this.unsupported("updateFrameworkDispatcher"); }
  public getLastError(): string | null { return this.unsupported("getLastError"); }
  public createGame(
    _callbacks: CnaGameCallbacks,
    _configuration: CnaGameConfiguration,
  ): NativeHandle { return this.unsupported("createGame"); }
  public runGame(
    _game: NativeHandle,
  ): Promise<void> { try { return this.unsupported("runGame"); } catch (error) { return Promise.reject(error) as Promise<void>; } }
  public runGameOneFrame(_game: NativeHandle): void { return this.unsupported("runGameOneFrame"); }
  public exitGame(_game: NativeHandle): void { return this.unsupported("exitGame"); }
  public destroyGame(_game: NativeHandle): void { return this.unsupported("destroyGame"); }
  public createGraphicsDeviceManager(
    _game: NativeHandle,
  ): NativeHandle { return this.unsupported("createGraphicsDeviceManager"); }
  public configureGraphicsDeviceManager(
    _manager: NativeHandle,
    _configuration: GraphicsManagerConfiguration,
  ): void { return this.unsupported("configureGraphicsDeviceManager"); }
  public applyGraphicsDeviceManagerChanges(
    _manager: NativeHandle,
  ): void { return this.unsupported("applyGraphicsDeviceManagerChanges"); }
  public toggleGraphicsDeviceManagerFullScreen(
    _manager: NativeHandle,
  ): void { return this.unsupported("toggleGraphicsDeviceManagerFullScreen"); }
  public createManagedGraphicsDevice(
    _manager: NativeHandle,
  ): void { return this.unsupported("createManagedGraphicsDevice"); }
  public beginGraphicsDeviceManagerDraw(
    _manager: NativeHandle,
  ): boolean { return this.unsupported("beginGraphicsDeviceManagerDraw"); }
  public endGraphicsDeviceManagerDraw(
    _manager: NativeHandle,
  ): void { return this.unsupported("endGraphicsDeviceManagerDraw"); }
  public destroyGraphicsDeviceManager(
    _manager: NativeHandle,
  ): void { return this.unsupported("destroyGraphicsDeviceManager"); }
  public borrowGraphicsDevice(
    _manager: NativeHandle,
  ): NativeHandle { return this.unsupported("borrowGraphicsDevice"); }
  public clearGraphicsDevice(
    _device: NativeHandle,
    _packedColor: number,
  ): void { return this.unsupported("clearGraphicsDevice"); }
  public presentGraphicsDevice(
    _device: NativeHandle,
  ): void { return this.unsupported("presentGraphicsDevice"); }
  public getRendererInfo(
    _device: NativeHandle,
  ): BackendRendererInfo { return this.unsupported("getRendererInfo"); }
  public createTexture2D(
    _device: NativeHandle,
    _width: number,
    _height: number,
    _mipMap: boolean,
    _surfaceFormat: number,
  ): NativeHandle { return this.unsupported("createTexture2D"); }
  public getTexture2DInfo(
    _texture: NativeHandle,
  ): Texture2DInfo { return this.unsupported("getTexture2DInfo"); }
  public createTexture2DFromEncodedMemory(
    _device: NativeHandle,
    _encoded: Uint8Array,
    _decode: {
    readonly Width: number;
    readonly Height: number;
    readonly Zoom: boolean;
} | null,
  ): NativeHandle { return this.unsupported("createTexture2DFromEncodedMemory"); }
  public setTexture2DData(
    _texture: NativeHandle,
    _transfer: Texture2DTransfer,
    _bytes: Uint8Array,
  ): void { return this.unsupported("setTexture2DData"); }
  public getTexture2DData(
    _texture: NativeHandle,
    _transfer: Texture2DTransfer,
  ): Uint8Array { return this.unsupported("getTexture2DData"); }
  public encodeTexture2D(
    _texture: NativeHandle,
    _imageFormat: number,
    _width: number,
    _height: number,
  ): Uint8Array { return this.unsupported("encodeTexture2D"); }
  public destroyTexture2D(_texture: NativeHandle): void { return this.unsupported("destroyTexture2D"); }
  public createSpriteBatch(
    _device: NativeHandle,
  ): NativeHandle { return this.unsupported("createSpriteBatch"); }
  public beginSpriteBatch(
    _spriteBatch: NativeHandle,
    _sortMode: number,
  ): void { return this.unsupported("beginSpriteBatch"); }
  public submitSpriteBatch(
    _spriteBatch: NativeHandle,
    _commands: readonly SpriteBatchCommand[],
  ): void { return this.unsupported("submitSpriteBatch"); }
  public endSpriteBatch(_spriteBatch: NativeHandle): void { return this.unsupported("endSpriteBatch"); }
  public destroySpriteBatch(
    _spriteBatch: NativeHandle,
  ): void { return this.unsupported("destroySpriteBatch"); }
  public createVertexBuffer(
    _device: NativeHandle,
    _vertexStride: number,
    _elements: readonly VertexElementSnapshot[],
    _vertexCount: number,
    _usage: number,
    _dynamic: boolean,
  ): NativeHandle { return this.unsupported("createVertexBuffer"); }
  public setVertexBufferRaw(
    _buffer: NativeHandle,
    _bytes: Uint8Array,
    _vertexCount: number,
    _vertexStride: number,
  ): void { return this.unsupported("setVertexBufferRaw"); }
  public getVertexBufferRaw(
    _buffer: NativeHandle,
    _vertexCount: number,
    _vertexStride: number,
  ): Uint8Array { return this.unsupported("getVertexBufferRaw"); }
  public destroyVertexBuffer(_buffer: NativeHandle): void { return this.unsupported("destroyVertexBuffer"); }
  public createIndexBuffer(
    _device: NativeHandle,
    _elementSize: number,
    _indexCount: number,
    _usage: number,
    _dynamic: boolean,
  ): NativeHandle { return this.unsupported("createIndexBuffer"); }
  public setIndexBufferRaw(
    _buffer: NativeHandle,
    _elementSize: number,
    _bytes: Uint8Array,
  ): void { return this.unsupported("setIndexBufferRaw"); }
  public getIndexBufferRaw(
    _buffer: NativeHandle,
    _elementSize: number,
    _indexCount: number,
  ): Uint8Array { return this.unsupported("getIndexBufferRaw"); }
  public destroyIndexBuffer(_buffer: NativeHandle): void { return this.unsupported("destroyIndexBuffer"); }
  public getKeyboardState(
    _playerIndex: PlayerIndex | null,
  ): KeyboardState { return this.unsupported("getKeyboardState"); }
  public getMouseState(): MouseState { return this.unsupported("getMouseState"); }
  public setMousePosition(_x: number, _y: number): void { return this.unsupported("setMousePosition"); }
  public get mouseWindowHandle(): bigint { return this.unsupported("mouseWindowHandle"); }
  public setMouseWindowHandle(_value: bigint): void { return this.unsupported("setMouseWindowHandle"); }
  public getGamePadState(
    _playerIndex: PlayerIndex,
    _deadZoneMode: GamePadDeadZone,
  ): GamePadState { return this.unsupported("getGamePadState"); }
  public getGamePadCapabilities(
    _playerIndex: PlayerIndex,
  ): GamePadCapabilities { return this.unsupported("getGamePadCapabilities"); }
  public setGamePadVibration(
    _playerIndex: PlayerIndex,
    _leftMotor: number,
    _rightMotor: number,
  ): boolean { return this.unsupported("setGamePadVibration"); }
  public getTouchState(): TouchCollection { return this.unsupported("getTouchState"); }
  public getTouchCapabilities(): TouchPanelCapabilities { return this.unsupported("getTouchCapabilities"); }
  public isGestureAvailable(): boolean { return this.unsupported("isGestureAvailable"); }
  public readGesture(): GestureSample { return this.unsupported("readGesture"); }
  public get touchWindowHandle(): bigint { return this.unsupported("touchWindowHandle"); }
  public setTouchWindowHandle(_value: bigint): void { return this.unsupported("setTouchWindowHandle"); }
}
